import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../bloc/report_bloc.dart';
import '../../../settings/presentation/bloc/settings_bloc.dart';
import '../../../inventory/presentation/bloc/inventory_bloc.dart';
import '../../../customers/presentation/bloc/customer_bloc.dart';
import '../../../../core/data/database/app_database.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

String _fmtDate(DateTime d) =>
    '${d.day.toString().padLeft(2, '0')}/${d.month.toString().padLeft(2, '0')}/${d.year}';

String _fmtDateTime(DateTime d) =>
    '${_fmtDate(d)}  ${d.hour.toString().padLeft(2, '0')}:${d.minute.toString().padLeft(2, '0')}';

DateTime _startOfDay(DateTime d) => DateTime(d.year, d.month, d.day);
DateTime _endOfDay(DateTime d) => DateTime(d.year, d.month, d.day, 23, 59, 59);

pw.Widget _pdfHeader(String businessName, String businessAddress,
    String businessPhone, pw.MemoryImage? logo) {
  return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.center, children: [
    if (logo != null) ...[
      pw.Center(child: pw.Image(logo, height: 50, fit: pw.BoxFit.contain)),
      pw.SizedBox(height: 6),
    ],
    pw.Text(businessName,
        style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        textAlign: pw.TextAlign.center),
    if (businessAddress.isNotEmpty)
      pw.Text(businessAddress,
          style: const pw.TextStyle(fontSize: 10), textAlign: pw.TextAlign.center),
    if (businessPhone.isNotEmpty)
      pw.Text(businessPhone,
          style: const pw.TextStyle(fontSize: 10), textAlign: pw.TextAlign.center),
    pw.SizedBox(height: 6),
    pw.Divider(thickness: 1),
  ]);
}

pw.Widget _pdfFooter() => pw.Column(children: [
      pw.Divider(thickness: 0.5),
      pw.Center(
        child: pw.Text(
          'Generated by POS Africa  •  ${_fmtDateTime(DateTime.now())}',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
        ),
      ),
    ]);

pw.TableRow _pdfHeaderRow(List<String> cells) => pw.TableRow(
      decoration: const pw.BoxDecoration(color: PdfColors.blueGrey700),
      children: cells
          .map((c) => pw.Padding(
                padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
                child: pw.Text(c,
                    style: pw.TextStyle(
                        fontSize: 9,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.white)),
              ))
          .toList(),
    );

pw.TableRow _pdfDataRow(List<String> cells, {bool isEven = false}) =>
    pw.TableRow(
      decoration: pw.BoxDecoration(
          color: isEven ? PdfColors.blueGrey50 : PdfColors.white),
      children: cells
          .map((c) => pw.Padding(
                padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
                child: pw.Text(c, style: const pw.TextStyle(fontSize: 9)),
              ))
          .toList(),
    );

// ─────────────────────────────────────────────────────────────────────────────
// Main Screen
// ─────────────────────────────────────────────────────────────────────────────

class ReportScreen extends StatefulWidget {
  const ReportScreen({super.key});

  @override
  State<ReportScreen> createState() => _ReportScreenState();
}

class _ReportScreenState extends State<ReportScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  // Overview
  DateTime _overviewDate = DateTime.now();

  // Sales Report
  DateTime _salesStart = DateTime.now().subtract(const Duration(days: 30));
  DateTime _salesEnd = DateTime.now();

  // Customer Purchases
  DateTime _custStart = DateTime.now().subtract(const Duration(days: 30));
  DateTime _custEnd = DateTime.now();
  int? _selectedCustomerId;

  // Receipts
  final _receiptSearchCtrl = TextEditingController();
  DateTime? _receiptStart;
  DateTime? _receiptEnd;

  // Product History
  DateTime _prodStart = DateTime.now().subtract(const Duration(days: 30));
  DateTime _prodEnd = DateTime.now();
  int? _selectedProductId;

  // Expenses
  DateTime _expStart = DateTime.now().subtract(const Duration(days: 30));
  DateTime _expEnd = DateTime.now();

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 8, vsync: this);
    _tabController.addListener(() {
      if (!_tabController.indexIsChanging) _loadTab(_tabController.index);
    });
    _loadTab(0);
  }

  @override
  void dispose() {
    _tabController.dispose();
    _receiptSearchCtrl.dispose();
    super.dispose();
  }

  void _loadTab(int i) {
    final b = context.read<ReportBloc>();
    switch (i) {
      case 0:
        b.add(LoadDailySalesSummary(_overviewDate));
        b.add(LoadInventoryValuation());
        break;
      case 1:
        b.add(LoadSalesReport(_startOfDay(_salesStart), _endOfDay(_salesEnd)));
        break;
      case 2:
        b.add(const LoadCustomerLedger());
        break;
      case 3:
        b.add(LoadCustomerPurchases(
          _startOfDay(_custStart), _endOfDay(_custEnd),
          customerId: _selectedCustomerId,
        ));
        break;
      case 4:
        b.add(FindReceiptsForReprint(
          _receiptSearchCtrl.text,
          start: _receiptStart,
          end: _receiptEnd,
        ));
        break;
      case 5:
        b.add(LoadProductSalesHistory(
          _startOfDay(_prodStart), _endOfDay(_prodEnd),
          productId: _selectedProductId,
        ));
        break;
      case 6:
        b.add(const LoadInventoryReport());
        break;
      case 7:
        b.add(LoadExpenseReport(_startOfDay(_expStart), _endOfDay(_expEnd)));
        break;
    }
  }

  Future<pw.MemoryImage?> _loadLogo(String path) async {
    if (path.isEmpty) return null;
    try {
      final f = File(path);
      if (await f.exists()) return pw.MemoryImage(await f.readAsBytes());
    } catch (_) {}
    return null;
  }

  Map<String, String> _settings(BuildContext ctx) {
    final s = ctx.read<SettingsBloc>().state;
    return s is SettingsLoaded ? s.settings : {};
  }

  // ── Date range picker helper ────────────────────────────────────────────
  Future<void> _pickDateRange(
    DateTime start,
    DateTime end,
    void Function(DateTime, DateTime) onPicked,
  ) async {
    final picked = await showDateRangePicker(
      context: context,
      firstDate: DateTime(2020),
      lastDate: DateTime.now().add(const Duration(days: 1)),
      initialDateRange: DateTimeRange(start: start, end: end),
    );
    if (picked != null) onPicked(picked.start, picked.end);
  }

  // ─────────────────────────────────────────────────────────────────────────
  // PDF EXPORTS
  // ─────────────────────────────────────────────────────────────────────────

  Future<void> _exportDailyReportPdf({bool salesOnly = false, bool stockOnly = false}) async {
    final s = _settings(context);
    final logo = await _loadLogo(s['business_logo_path'] ?? '');
    final state = context.read<ReportBloc>().state;
    if (state is! ReportDataState) return;

    final doc = pw.Document();
    final date = _fmtDate(_overviewDate);

    doc.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      build: (ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _pdfHeader(s['business_name'] ?? 'POS Africa',
              s['business_address'] ?? '', s['business_phone'] ?? '', logo),
          pw.Center(
            child: pw.Text('Daily Report  —  $date',
                style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold)),
          ),
          pw.SizedBox(height: 14),
          if (!stockOnly) ...[
            pw.Text('Sales Summary',
                style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blueGrey800)),
            pw.SizedBox(height: 6),
            if (state.dailySummary != null) ...[
              _buildSummaryTable(state.dailySummary!),
            ] else
              pw.Text('No sales data.', style: const pw.TextStyle(fontSize: 10)),
            pw.SizedBox(height: 18),
          ],
          if (!salesOnly) ...[
            pw.Text('Stock / Inventory Status',
                style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blueGrey800)),
            pw.SizedBox(height: 6),
            if (state.inventoryReport != null && state.inventoryReport!.isNotEmpty)
              _buildInventoryTable(state.inventoryReport!)
            else if (state.inventoryValuation != null)
              pw.Text(
                  'Total Inventory Value: CDF ${state.inventoryValuation!.toStringAsFixed(0)}',
                  style: const pw.TextStyle(fontSize: 10))
            else
              pw.Text('Load inventory tab first.', style: const pw.TextStyle(fontSize: 10)),
          ],
          pw.Spacer(),
          _pdfFooter(),
        ],
      ),
    ));

    await Printing.layoutPdf(
      onLayout: (_) => doc.save(),
      name: 'Daily_Report_${date.replaceAll('/', '-')}',
    );
  }

  pw.Widget _buildSummaryTable(Map<String, double> s) => pw.Table(
        border: pw.TableBorder.all(color: PdfColors.grey300),
        columnWidths: {
          0: const pw.FlexColumnWidth(3),
          1: const pw.FlexColumnWidth(2),
        },
        children: [
          _pdfHeaderRow(['Metric', 'Value']),
          _pdfDataRow(['Transactions', (s['count'] ?? 0).toStringAsFixed(0)]),
          _pdfDataRow(['Total Revenue', 'CDF ${(s['total'] ?? 0).toStringAsFixed(0)}'], isEven: true),
          _pdfDataRow(['Subtotal', 'CDF ${(s['subtotal'] ?? 0).toStringAsFixed(0)}']),
          _pdfDataRow(['Total Discounts', 'CDF ${(s['discount'] ?? 0).toStringAsFixed(0)}'], isEven: true),
          _pdfDataRow(['VAT Collected', 'CDF ${(s['tax'] ?? 0).toStringAsFixed(0)}']),
        ],
      );

  pw.Widget _buildInventoryTable(List<Map<String, dynamic>> rows) => pw.Table(
        border: pw.TableBorder.all(color: PdfColors.grey300),
        columnWidths: {
          0: const pw.FlexColumnWidth(3),
          1: const pw.FlexColumnWidth(2),
          2: const pw.FlexColumnWidth(1.5),
          3: const pw.FlexColumnWidth(1.5),
          4: const pw.FlexColumnWidth(1.5),
        },
        children: [
          _pdfHeaderRow(['Product', 'Category', 'Stock', 'Selling', 'Value (CDF)']),
          ...rows.asMap().entries.map((e) => _pdfDataRow([
                e.value['name']?.toString() ?? '',
                e.value['category']?.toString() ?? '',
                (e.value['stockQuantity'] as double? ?? 0).toStringAsFixed(0),
                'CDF ${(e.value['sellingPrice'] as double? ?? 0).toStringAsFixed(0)}',
                'CDF ${(e.value['totalValue'] as double? ?? 0).toStringAsFixed(0)}',
              ], isEven: e.key.isEven)),
        ],
      );

  Future<void> _exportSalesPdf(List<Map<String, dynamic>> rows) async {
    final s = _settings(context);
    final logo = await _loadLogo(s['business_logo_path'] ?? '');
    final doc = pw.Document();
    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      header: (_) => pw.Column(children: [
        _pdfHeader(s['business_name'] ?? 'POS Africa',
            s['business_address'] ?? '', s['business_phone'] ?? '', logo),
        pw.Text('Sales Report  •  ${_fmtDate(_salesStart)} – ${_fmtDate(_salesEnd)}',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
      ]),
      footer: (_) => _pdfFooter(),
      build: (_) => [
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(2.5),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(2.5),
            3: const pw.FlexColumnWidth(2),
            4: const pw.FlexColumnWidth(1.5),
          },
          children: [
            _pdfHeaderRow(['Invoice #', 'Date', 'Customer', 'Total (CDF)', 'Status']),
            ...rows.asMap().entries.map((e) {
              final r = e.value;
              return _pdfDataRow([
                r['transactionNumber']?.toString() ?? '',
                _fmtDate(r['saleDate'] as DateTime),
                r['customerName']?.toString() ?? 'Walk-in',
                'CDF ${(r['grandTotal'] as double? ?? 0).toStringAsFixed(0)}',
                r['status']?.toString() ?? '',
              ], isEven: e.key.isEven);
            }),
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.blueGrey100),
              children: [
                pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text('TOTAL (${rows.length} transactions)',
                        style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold))),
                pw.SizedBox(),
                pw.SizedBox(),
                pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                        'CDF ${rows.fold<double>(0, (s, r) => s + (r['grandTotal'] as double? ?? 0)).toStringAsFixed(0)}',
                        style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold))),
                pw.SizedBox(),
              ],
            ),
          ],
        ),
      ],
    ));
    await Printing.layoutPdf(
      onLayout: (_) => doc.save(),
      name: 'Sales_Report_${_fmtDate(_salesStart).replaceAll('/', '-')}_${_fmtDate(_salesEnd).replaceAll('/', '-')}',
    );
  }

  Future<void> _exportCustomerLedgerPdf(List<Map<String, dynamic>> rows) async {
    final s = _settings(context);
    final logo = await _loadLogo(s['business_logo_path'] ?? '');
    final doc = pw.Document();
    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      header: (_) => pw.Column(children: [
        _pdfHeader(s['business_name'] ?? 'POS Africa',
            s['business_address'] ?? '', s['business_phone'] ?? '', logo),
        pw.Text('Customer Ledger',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
      ]),
      footer: (_) => _pdfFooter(),
      build: (_) => [
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(2.5),
            1: const pw.FlexColumnWidth(1.5),
            2: const pw.FlexColumnWidth(1.5),
            3: const pw.FlexColumnWidth(1.5),
            4: const pw.FlexColumnWidth(2),
          },
          children: [
            _pdfHeaderRow(['Customer', 'Phone', 'Total Spent', 'Balance Owed', 'Last Purchase']),
            ...rows.asMap().entries.map((e) {
              final r = e.value;
              return _pdfDataRow([
                r['fullName']?.toString() ?? '',
                r['phone']?.toString() ?? '—',
                'CDF ${(r['totalSpent'] as double? ?? 0).toStringAsFixed(0)}',
                'CDF ${(r['balanceOwed'] as double? ?? 0).toStringAsFixed(0)}',
                r['lastPurchase'] != null ? _fmtDate(r['lastPurchase'] as DateTime) : '—',
              ], isEven: e.key.isEven);
            }),
          ],
        ),
      ],
    ));
    await Printing.layoutPdf(
        onLayout: (_) => doc.save(), name: 'Customer_Ledger');
  }

  Future<void> _exportCustomerPurchasesPdf(List<Map<String, dynamic>> rows) async {
    final s = _settings(context);
    final logo = await _loadLogo(s['business_logo_path'] ?? '');
    final doc = pw.Document();
    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      header: (_) => pw.Column(children: [
        _pdfHeader(s['business_name'] ?? 'POS Africa',
            s['business_address'] ?? '', s['business_phone'] ?? '', logo),
        pw.Text('Customer Purchases  •  ${_fmtDate(_custStart)} – ${_fmtDate(_custEnd)}',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
      ]),
      footer: (_) => _pdfFooter(),
      build: (_) => [
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(2.5),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(2.5),
            3: const pw.FlexColumnWidth(2),
          },
          children: [
            _pdfHeaderRow(['Invoice #', 'Date', 'Customer', 'Total (CDF)']),
            ...rows.asMap().entries.map((e) {
              final r = e.value;
              return _pdfDataRow([
                r['transactionNumber']?.toString() ?? '',
                _fmtDate(r['saleDate'] as DateTime),
                r['customerName']?.toString() ?? '',
                'CDF ${(r['grandTotal'] as double? ?? 0).toStringAsFixed(0)}',
              ], isEven: e.key.isEven);
            }),
          ],
        ),
      ],
    ));
    await Printing.layoutPdf(
        onLayout: (_) => doc.save(), name: 'Customer_Purchases');
  }

  Future<void> _exportProductHistoryPdf(List<Map<String, dynamic>> rows) async {
    final s = _settings(context);
    final logo = await _loadLogo(s['business_logo_path'] ?? '');
    final doc = pw.Document();
    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      header: (_) => pw.Column(children: [
        _pdfHeader(s['business_name'] ?? 'POS Africa',
            s['business_address'] ?? '', s['business_phone'] ?? '', logo),
        pw.Text('Product Sales History  •  ${_fmtDate(_prodStart)} – ${_fmtDate(_prodEnd)}',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
      ]),
      footer: (_) => _pdfFooter(),
      build: (_) => [
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(3),
            1: const pw.FlexColumnWidth(1.5),
            2: const pw.FlexColumnWidth(1.5),
            3: const pw.FlexColumnWidth(2),
            4: const pw.FlexColumnWidth(1.5),
            5: const pw.FlexColumnWidth(1.5),
          },
          children: [
            _pdfHeaderRow(
                ['Product', 'Qty Sold', 'Times', 'Revenue (CDF)', 'Current Stock', 'First Sale']),
            ...rows.asMap().entries.map((e) {
              final r = e.value;
              return _pdfDataRow([
                r['name']?.toString() ?? '',
                (r['totalQtySold'] as double? ?? 0).toStringAsFixed(0),
                (r['timesTransacted'] as int? ?? 0).toString(),
                'CDF ${(r['totalRevenue'] as double? ?? 0).toStringAsFixed(0)}',
                (r['stockQuantity'] as double? ?? 0).toStringAsFixed(0),
                r['firstSale'] != null ? _fmtDate(r['firstSale'] as DateTime) : '—',
              ], isEven: e.key.isEven);
            }),
          ],
        ),
      ],
    ));
    await Printing.layoutPdf(
        onLayout: (_) => doc.save(), name: 'Product_History');
  }

  Future<void> _exportInventoryPdf(List<Map<String, dynamic>> rows) async {
    final s = _settings(context);
    final logo = await _loadLogo(s['business_logo_path'] ?? '');
    final doc = pw.Document();
    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      header: (_) => pw.Column(children: [
        _pdfHeader(s['business_name'] ?? 'POS Africa',
            s['business_address'] ?? '', s['business_phone'] ?? '', logo),
        pw.Text('Inventory Report  •  ${_fmtDate(DateTime.now())}',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
      ]),
      footer: (_) => _pdfFooter(),
      build: (_) => [_buildInventoryTable(rows)],
    ));
    await Printing.layoutPdf(
        onLayout: (_) => doc.save(), name: 'Inventory_Report');
  }

  Future<void> _exportExpensePdf(List<Map<String, dynamic>> rows) async {
    final s = _settings(context);
    final logo = await _loadLogo(s['business_logo_path'] ?? '');
    final doc = pw.Document();
    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      header: (_) => pw.Column(children: [
        _pdfHeader(s['business_name'] ?? 'POS Africa',
            s['business_address'] ?? '', s['business_phone'] ?? '', logo),
        pw.Text('Expense Report  •  ${_fmtDate(_expStart)} – ${_fmtDate(_expEnd)}',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
      ]),
      footer: (_) => _pdfFooter(),
      build: (_) => [
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(1.5),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(3),
            3: const pw.FlexColumnWidth(1.5),
          },
          children: [
            _pdfHeaderRow(['Date', 'Category', 'Description', 'Amount (CDF)']),
            ...rows.asMap().entries.map((e) {
              final r = e.value;
              return _pdfDataRow([
                _fmtDate(r['date'] as DateTime),
                r['category']?.toString() ?? '—',
                r['description']?.toString() ?? '',
                'CDF ${(r['amount'] as double? ?? 0).toStringAsFixed(0)}',
              ], isEven: e.key.isEven);
            }),
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.blueGrey100),
              children: [
                pw.SizedBox(),
                pw.SizedBox(),
                pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text('TOTAL',
                        style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold))),
                pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                        'CDF ${rows.fold<double>(0, (s, r) => s + (r['amount'] as double? ?? 0)).toStringAsFixed(0)}',
                        style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold))),
              ],
            ),
          ],
        ),
      ],
    ));
    await Printing.layoutPdf(
        onLayout: (_) => doc.save(), name: 'Expense_Report');
  }

  Future<void> _reprintSaleDetail(Map<String, dynamic> detail) async {
    final s = _settings(context);
    final logo = await _loadLogo(s['business_logo_path'] ?? '');
    final businessName = s['business_name'] ?? 'POS Africa';
    final businessAddress = s['business_address'] ?? '';
    final businessPhone = s['business_phone'] ?? '';
    final dualCurrency = (s['dual_currency_enabled'] ?? 'false') == 'true';
    final footer = s['receipt_footer'] ?? 'Merci pour votre achat!';
    final vatEnabled = (s['vat_enabled'] ?? 'false') == 'true';
    final widthMm = double.tryParse(s['receipt_paper_width_mm'] ?? '80') ?? 80;
    final vatPct = double.tryParse(s['vat_percentage'] ?? '16') ?? 16;
    final vatNumber = s['business_vat_number'] ?? '';

    final doc = pw.Document();

    pw.TextStyle bold(double sz) =>
        pw.TextStyle(fontSize: sz, fontWeight: pw.FontWeight.bold);
    pw.TextStyle norm(double sz) => pw.TextStyle(fontSize: sz);

    final pageWidth = widthMm * PdfPageFormat.mm;
    final margin = (widthMm >= 100 ? 8.0 : 4.0) * PdfPageFormat.mm;

    final txn = detail['transactionNumber']?.toString() ?? '';
    final saleDate = detail['saleDate'] as DateTime? ?? DateTime.now();
    final lines = (detail['lines'] as List?)?.cast<Map<String, dynamic>>() ?? [];
    final subtotal = (detail['subtotal'] as double? ?? 0);
    final discount = (detail['discountAmount'] as double? ?? 0);
    final vatAmount = (detail['vatAmount'] as double? ?? 0);
    final grandTotal = (detail['grandTotal'] as double? ?? 0);
    final grandTotalUsd = (detail['grandTotalUsd'] as double? ?? 0);
    final exchangeRate = (detail['exchangeRate'] as double? ?? 2850);
    final method = detail['paymentMethod']?.toString() ?? 'CASH';
    final tendered = (detail['amountTendered'] as double? ?? grandTotal);
    final change = (detail['changeDue'] as double? ?? 0.0);
    final customerName = detail['customerName']?.toString();

    doc.addPage(pw.Page(
      pageFormat: PdfPageFormat(pageWidth, double.infinity, marginAll: margin),
      build: (_) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          if (logo != null) ...[
            pw.Center(child: pw.Image(logo, height: 50, fit: pw.BoxFit.contain)),
            pw.SizedBox(height: 4),
          ],
          pw.Text(businessName, style: bold(13), textAlign: pw.TextAlign.center),
          if (businessAddress.isNotEmpty)
            pw.Text(businessAddress, style: norm(8), textAlign: pw.TextAlign.center),
          if (businessPhone.isNotEmpty)
            pw.Text(businessPhone, style: norm(8), textAlign: pw.TextAlign.center),
          if (vatEnabled && vatNumber.isNotEmpty)
            pw.Text('TVA No: $vatNumber', style: norm(8), textAlign: pw.TextAlign.center),
          pw.SizedBox(height: 4),
          pw.Center(
            child: pw.Text('*** REPRINT ***',
                style: pw.TextStyle(fontSize: 8, color: PdfColors.orange700)),
          ),
          pw.Divider(thickness: 0.5),
          if (customerName != null)
            pw.Text('Client: $customerName', style: norm(8)),
          pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
            pw.Text(txn, style: norm(8)),
            pw.Text(_fmtDateTime(saleDate), style: norm(8)),
          ]),
          pw.Divider(thickness: 0.5),
          ...lines.map((l) => pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 2),
                child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                  pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Expanded(
                            child: pw.Text(l['productName']?.toString() ?? '', style: norm(9))),
                        pw.Text('CDF ${(l['lineTotal'] as double? ?? 0).toStringAsFixed(0)}',
                            style: norm(9)),
                      ]),
                  pw.Text(
                      '  ${(l['quantity'] as double? ?? 0).toStringAsFixed(0)} x CDF ${(l['unitPrice'] as double? ?? 0).toStringAsFixed(0)}',
                      style: norm(8)),
                ]),
              )),
          pw.Divider(thickness: 0.5),
          pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [pw.Text('Sous-total:', style: norm(9)), pw.Text('CDF ${subtotal.toStringAsFixed(0)}', style: norm(9))]),
          if (discount > 0)
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [pw.Text('Remise:', style: norm(9)), pw.Text('-CDF ${discount.toStringAsFixed(0)}', style: norm(9))]),
          if (vatEnabled && vatAmount > 0) ...[
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [pw.Text('TVA ($vatPct%):', style: norm(9)), pw.Text('CDF ${vatAmount.toStringAsFixed(0)}', style: norm(9))]),
          ],
          pw.SizedBox(height: 3),
          pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [pw.Text('TOTAL:', style: bold(11)), pw.Text('CDF ${grandTotal.toStringAsFixed(0)}', style: bold(11))]),
          if (dualCurrency)
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [pw.Text('USD:', style: norm(9)), pw.Text('\$${grandTotalUsd.toStringAsFixed(2)}', style: norm(9))]),
          pw.Divider(thickness: 0.5),
          pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [pw.Text('Paiement:', style: norm(9)), pw.Text(method, style: norm(9))]),
          pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [pw.Text('Reçu:', style: norm(9)), pw.Text('CDF ${tendered.toStringAsFixed(0)}', style: norm(9))]),
          if (change > 0)
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [pw.Text('Monnaie:', style: norm(9)), pw.Text('CDF ${change.toStringAsFixed(0)}', style: bold(9))]),
          pw.SizedBox(height: 6),
          pw.Center(child: pw.Text(footer, style: norm(9), textAlign: pw.TextAlign.center)),
          pw.SizedBox(height: 4),
        ],
      ),
    ));

    await Printing.layoutPdf(
        onLayout: (_) => doc.save(), name: 'Receipt_${txn}');
  }

  // ─────────────────────────────────────────────────────────────────────────
  // BUILD
  // ─────────────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Reports & Analytics'),
        bottom: TabBar(
          controller: _tabController,
          isScrollable: true,
          tabAlignment: TabAlignment.start,
          tabs: const [
            Tab(icon: Icon(Icons.dashboard_rounded, size: 16), text: 'Overview'),
            Tab(icon: Icon(Icons.receipt_long_rounded, size: 16), text: 'Sales'),
            Tab(icon: Icon(Icons.people_rounded, size: 16), text: 'Customer Ledger'),
            Tab(icon: Icon(Icons.shopping_cart_rounded, size: 16), text: 'Purchases'),
            Tab(icon: Icon(Icons.find_in_page_rounded, size: 16), text: 'Receipts'),
            Tab(icon: Icon(Icons.bar_chart_rounded, size: 16), text: 'Products'),
            Tab(icon: Icon(Icons.inventory_2_rounded, size: 16), text: 'Inventory'),
            Tab(icon: Icon(Icons.money_off_rounded, size: 16), text: 'Expenses'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _OverviewTab(
            date: _overviewDate,
            onDateChanged: (d) => setState(() {
              _overviewDate = d;
              _loadTab(0);
            }),
            onTodaySales: () => _exportDailyReportPdf(salesOnly: true),
            onTodayStock: () {
              context.read<ReportBloc>().add(const LoadInventoryReport());
              _exportDailyReportPdf(stockOnly: true);
            },
            onTodayBoth: () {
              context.read<ReportBloc>().add(const LoadInventoryReport());
              _exportDailyReportPdf();
            },
          ),
          _SalesReportTab(
            start: _salesStart,
            end: _salesEnd,
            onPickRange: () => _pickDateRange(_salesStart, _salesEnd, (s, e) {
              setState(() { _salesStart = s; _salesEnd = e; });
              _loadTab(1);
            }),
            onExportPdf: (rows) => _exportSalesPdf(rows),
          ),
          _CustomerLedgerTab(
            onExportPdf: (rows) => _exportCustomerLedgerPdf(rows),
          ),
          _CustomerPurchasesTab(
            start: _custStart,
            end: _custEnd,
            selectedCustomerId: _selectedCustomerId,
            onPickRange: () => _pickDateRange(_custStart, _custEnd, (s, e) {
              setState(() { _custStart = s; _custEnd = e; });
              _loadTab(3);
            }),
            onCustomerChanged: (id) {
              setState(() => _selectedCustomerId = id);
              _loadTab(3);
            },
            onExportPdf: (rows) => _exportCustomerPurchasesPdf(rows),
          ),
          _ReceiptsTab(
            searchCtrl: _receiptSearchCtrl,
            start: _receiptStart,
            end: _receiptEnd,
            onSearch: () => _loadTab(4),
            onPickRange: () => _pickDateRange(
              _receiptStart ?? DateTime.now().subtract(const Duration(days: 30)),
              _receiptEnd ?? DateTime.now(),
              (s, e) {
                setState(() { _receiptStart = s; _receiptEnd = e; });
                context.read<ReportBloc>().add(FindReceiptsForReprint(
                  _receiptSearchCtrl.text,
                  start: s,
                  end: e,
                ));
              },
            ),
            onReprint: (saleId) {
              context.read<ReportBloc>().add(LoadSaleDetail(saleId));
              // Watch for the saleDetail to load, then print
              _waitAndReprint(context, saleId);
            },
          ),
          _ProductHistoryTab(
            start: _prodStart,
            end: _prodEnd,
            selectedProductId: _selectedProductId,
            onPickRange: () => _pickDateRange(_prodStart, _prodEnd, (s, e) {
              setState(() { _prodStart = s; _prodEnd = e; });
              _loadTab(5);
            }),
            onProductChanged: (id) {
              setState(() => _selectedProductId = id);
              _loadTab(5);
            },
            onExportPdf: (rows) => _exportProductHistoryPdf(rows),
          ),
          _InventoryReportTab(
            onRefresh: () => _loadTab(6),
            onExportPdf: (rows) => _exportInventoryPdf(rows),
          ),
          _ExpenseReportTab(
            start: _expStart,
            end: _expEnd,
            onPickRange: () => _pickDateRange(_expStart, _expEnd, (s, e) {
              setState(() { _expStart = s; _expEnd = e; });
              _loadTab(7);
            }),
            onExportPdf: (rows) => _exportExpensePdf(rows),
          ),
        ],
      ),
    );
  }

  void _waitAndReprint(BuildContext context, int saleId) {
    // Listen to next state that has the detail loaded
    final bloc = context.read<ReportBloc>();
    bloc.stream.firstWhere((s) =>
      s is ReportDataState && s.saleDetail?['id'] == saleId && !s.isLoadingSaleDetail
    ).then((state) {
      final detail = (state as ReportDataState).saleDetail;
      if (detail != null) _reprintSaleDetail(detail);
    });
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tab widgets
// ─────────────────────────────────────────────────────────────────────────────

class _OverviewTab extends StatelessWidget {
  final DateTime date;
  final ValueChanged<DateTime> onDateChanged;
  final VoidCallback onTodaySales;
  final VoidCallback onTodayStock;
  final VoidCallback onTodayBoth;

  const _OverviewTab({
    required this.date,
    required this.onDateChanged,
    required this.onTodaySales,
    required this.onTodayStock,
    required this.onTodayBoth,
  });

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ReportBloc, ReportState>(
      builder: (context, state) {
        final ds = state is ReportDataState ? state : const ReportDataState();
        return SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Quick report buttons
              Card(
                color: Theme.of(context).colorScheme.primaryContainer.withAlpha(60),
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Quick Today\'s Reports',
                          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                              fontWeight: FontWeight.bold)),
                      const SizedBox(height: 12),
                      Wrap(
                        spacing: 12,
                        runSpacing: 8,
                        children: [
                          ElevatedButton.icon(
                            onPressed: onTodaySales,
                            icon: const Icon(Icons.receipt_long_rounded, size: 18),
                            label: const Text('Today\'s Sales PDF'),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.green,
                              foregroundColor: Colors.white,
                            ),
                          ),
                          ElevatedButton.icon(
                            onPressed: onTodayStock,
                            icon: const Icon(Icons.inventory_2_rounded, size: 18),
                            label: const Text('Today\'s Stock PDF'),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.blue,
                              foregroundColor: Colors.white,
                            ),
                          ),
                          ElevatedButton.icon(
                            onPressed: onTodayBoth,
                            icon: const Icon(Icons.picture_as_pdf_rounded, size: 18),
                            label: const Text('Full Day Report PDF'),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.deepPurple,
                              foregroundColor: Colors.white,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),
              Row(children: [
                Text('Daily Summary', style: Theme.of(context).textTheme.titleLarge),
                const SizedBox(width: 16),
                TextButton.icon(
                  icon: const Icon(Icons.calendar_today, size: 16),
                  label: Text(_fmtDate(date)),
                  onPressed: () async {
                    final picked = await showDatePicker(
                      context: context,
                      initialDate: date,
                      firstDate: DateTime(2020),
                      lastDate: DateTime.now(),
                    );
                    if (picked != null) onDateChanged(picked);
                  },
                ),
              ]),
              const SizedBox(height: 16),
              if (ds.isLoadingDaily)
                const LinearProgressIndicator()
              else if (ds.dailySummary != null)
                _SummaryCards(ds.dailySummary!)
              else
                const Text('No sales data for this date.'),
              const SizedBox(height: 32),
              Text('Inventory Value', style: Theme.of(context).textTheme.titleLarge),
              const SizedBox(height: 16),
              if (ds.isLoadingInventory)
                const LinearProgressIndicator()
              else if (ds.inventoryValuation != null)
                Card(
                  child: Padding(
                    padding: const EdgeInsets.all(20),
                    child: Row(children: [
                      const Icon(Icons.inventory_rounded, size: 32, color: Colors.blue),
                      const SizedBox(width: 16),
                      Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                        const Text('Total Inventory Value (Cost)',
                            style: TextStyle(color: Colors.grey)),
                        Text(
                          'CDF ${ds.inventoryValuation!.toStringAsFixed(0)}',
                          style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
                        ),
                      ]),
                    ]),
                  ),
                ),
            ],
          ),
        );
      },
    );
  }
}

class _SummaryCards extends StatelessWidget {
  final Map<String, double> s;
  const _SummaryCards(this.s);

  @override
  Widget build(BuildContext context) {
    final cards = [
      ('Transactions', s['count']?.toStringAsFixed(0) ?? '0', Icons.receipt, Colors.teal),
      ('Total Revenue', 'CDF ${s['total']?.toStringAsFixed(0) ?? '0'}', Icons.payments_rounded, Colors.green),
      ('Discounts', 'CDF ${s['discount']?.toStringAsFixed(0) ?? '0'}', Icons.local_offer_rounded, Colors.orange),
      ('VAT Collected', 'CDF ${s['tax']?.toStringAsFixed(0) ?? '0'}', Icons.percent_rounded, Colors.purple),
    ];
    return Wrap(
      spacing: 12,
      runSpacing: 12,
      children: cards.map((c) => SizedBox(
        width: 200,
        child: Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Icon(c.$3, color: c.$4, size: 28),
              const SizedBox(height: 10),
              Text(c.$1, style: const TextStyle(color: Colors.grey, fontSize: 12)),
              const SizedBox(height: 6),
              Text(c.$2, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            ]),
          ),
        ),
      )).toList(),
    );
  }
}

// ── Sales Report Tab ──────────────────────────────────────────────────────────

class _SalesReportTab extends StatelessWidget {
  final DateTime start, end;
  final VoidCallback onPickRange;
  final void Function(List<Map<String, dynamic>>) onExportPdf;

  const _SalesReportTab({
    required this.start,
    required this.end,
    required this.onPickRange,
    required this.onExportPdf,
  });

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ReportBloc, ReportState>(
      builder: (context, state) {
        final ds = state is ReportDataState ? state : const ReportDataState();
        final rows = ds.salesReport ?? [];
        return Column(children: [
          _ReportToolbar(
            label: '${_fmtDate(start)} – ${_fmtDate(end)}',
            onPickRange: onPickRange,
            isLoading: ds.isLoadingSalesReport,
            hasData: rows.isNotEmpty,
            onExport: () => onExportPdf(rows),
          ),
          Expanded(
            child: ds.isLoadingSalesReport
                ? const Center(child: CircularProgressIndicator())
                : rows.isEmpty
                    ? const Center(child: Text('No sales in selected range.'))
                    : SingleChildScrollView(
                        padding: const EdgeInsets.all(16),
                        child: SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: DataTable(
                            columnSpacing: 20,
                            columns: const [
                              DataColumn(label: Text('Invoice #')),
                              DataColumn(label: Text('Date')),
                              DataColumn(label: Text('Customer')),
                              DataColumn(label: Text('Total CDF'), numeric: true),
                              DataColumn(label: Text('VAT CDF'), numeric: true),
                              DataColumn(label: Text('Status')),
                            ],
                            rows: rows.map((r) => DataRow(cells: [
                              DataCell(Text(r['transactionNumber']?.toString() ?? '')),
                              DataCell(Text(_fmtDate(r['saleDate'] as DateTime))),
                              DataCell(Text(r['customerName']?.toString() ?? 'Walk-in')),
                              DataCell(Text('CDF ${(r['grandTotal'] as double? ?? 0).toStringAsFixed(0)}')),
                              DataCell(Text('CDF ${(r['vatAmount'] as double? ?? 0).toStringAsFixed(0)}')),
                              DataCell(
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                                  decoration: BoxDecoration(
                                    color: r['status'] == 'COMPLETED'
                                        ? Colors.green.withAlpha(30)
                                        : Colors.red.withAlpha(30),
                                    borderRadius: BorderRadius.circular(8),
                                  ),
                                  child: Text(r['status']?.toString() ?? '',
                                      style: TextStyle(
                                          color: r['status'] == 'COMPLETED'
                                              ? Colors.green
                                              : Colors.red,
                                          fontSize: 12)),
                                ),
                              ),
                            ])).toList(),
                          ),
                        ),
                      ),
          ),
          if (rows.isNotEmpty)
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 8),
              color: Theme.of(context).colorScheme.surfaceContainerLow,
              child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
                Text('${rows.length} transactions'),
                Text(
                  'Total: CDF ${rows.fold<double>(0, (s, r) => s + (r['grandTotal'] as double? ?? 0)).toStringAsFixed(0)}',
                  style: const TextStyle(fontWeight: FontWeight.bold),
                ),
              ]),
            ),
        ]);
      },
    );
  }
}

// ── Customer Ledger Tab ───────────────────────────────────────────────────────

class _CustomerLedgerTab extends StatelessWidget {
  final void Function(List<Map<String, dynamic>>) onExportPdf;
  const _CustomerLedgerTab({required this.onExportPdf});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ReportBloc, ReportState>(
      builder: (context, state) {
        final ds = state is ReportDataState ? state : const ReportDataState();
        final rows = ds.customerLedger ?? [];
        return Column(children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
            child: Row(children: [
              TextButton.icon(
                icon: const Icon(Icons.refresh, size: 16),
                label: const Text('Refresh'),
                onPressed: () => context.read<ReportBloc>().add(const LoadCustomerLedger()),
              ),
              const Spacer(),
              if (rows.isNotEmpty)
                FilledButton.icon(
                  onPressed: () => onExportPdf(rows),
                  icon: const Icon(Icons.picture_as_pdf_rounded, size: 16),
                  label: const Text('Export PDF'),
                ),
            ]),
          ),
          Expanded(
            child: ds.isLoadingCustomerLedger
                ? const Center(child: CircularProgressIndicator())
                : rows.isEmpty
                    ? const Center(child: Text('No customers found.'))
                    : SingleChildScrollView(
                        padding: const EdgeInsets.all(16),
                        child: SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: DataTable(
                            columnSpacing: 20,
                            columns: const [
                              DataColumn(label: Text('Customer')),
                              DataColumn(label: Text('Phone')),
                              DataColumn(label: Text('Purchases'), numeric: true),
                              DataColumn(label: Text('Total Spent'), numeric: true),
                              DataColumn(label: Text('Balance Owed'), numeric: true),
                              DataColumn(label: Text('Last Purchase')),
                            ],
                            rows: rows.map((r) => DataRow(cells: [
                              DataCell(Text(r['fullName']?.toString() ?? '')),
                              DataCell(Text(r['phone']?.toString() ?? '—')),
                              DataCell(Text((r['totalPurchases'] as int? ?? 0).toString())),
                              DataCell(Text('CDF ${(r['totalSpent'] as double? ?? 0).toStringAsFixed(0)}')),
                              DataCell(
                                Text(
                                  'CDF ${(r['balanceOwed'] as double? ?? 0).toStringAsFixed(0)}',
                                  style: TextStyle(
                                    color: (r['balanceOwed'] as double? ?? 0) > 0
                                        ? Colors.red
                                        : null,
                                    fontWeight: (r['balanceOwed'] as double? ?? 0) > 0
                                        ? FontWeight.bold
                                        : null,
                                  ),
                                ),
                              ),
                              DataCell(Text(r['lastPurchase'] != null
                                  ? _fmtDate(r['lastPurchase'] as DateTime)
                                  : '—')),
                            ])).toList(),
                          ),
                        ),
                      ),
          ),
        ]);
      },
    );
  }
}

// ── Customer Purchases Tab ────────────────────────────────────────────────────

class _CustomerPurchasesTab extends StatelessWidget {
  final DateTime start, end;
  final int? selectedCustomerId;
  final VoidCallback onPickRange;
  final ValueChanged<int?> onCustomerChanged;
  final void Function(List<Map<String, dynamic>>) onExportPdf;

  const _CustomerPurchasesTab({
    required this.start,
    required this.end,
    required this.selectedCustomerId,
    required this.onPickRange,
    required this.onCustomerChanged,
    required this.onExportPdf,
  });

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ReportBloc, ReportState>(
      builder: (context, state) {
        final ds = state is ReportDataState ? state : const ReportDataState();
        final rows = ds.customerPurchases ?? [];
        return BlocBuilder<CustomerBloc, CustomerState>(
          builder: (context, custState) {
            final customers = custState is CustomerLoaded ? custState.customers : <Customer>[];
            return Column(children: [
              Padding(
                padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
                child: Wrap(spacing: 12, crossAxisAlignment: WrapCrossAlignment.center, children: [
                  TextButton.icon(
                    icon: const Icon(Icons.date_range, size: 16),
                    label: Text('${_fmtDate(start)} – ${_fmtDate(end)}'),
                    onPressed: onPickRange,
                  ),
                  DropdownButton<int?>(
                    value: selectedCustomerId,
                    hint: const Text('All Customers'),
                    items: [
                      const DropdownMenuItem(value: null, child: Text('All Customers')),
                      ...customers.map((c) => DropdownMenuItem(
                          value: c.id, child: Text(c.fullName))),
                    ],
                    onChanged: onCustomerChanged,
                  ),
                  if (rows.isNotEmpty)
                    FilledButton.icon(
                      onPressed: () => onExportPdf(rows),
                      icon: const Icon(Icons.picture_as_pdf_rounded, size: 16),
                      label: const Text('Export PDF'),
                    ),
                ]),
              ),
              Expanded(
                child: ds.isLoadingCustomerPurchases
                    ? const Center(child: CircularProgressIndicator())
                    : rows.isEmpty
                        ? const Center(child: Text('No purchases found.'))
                        : SingleChildScrollView(
                            padding: const EdgeInsets.all(16),
                            child: SingleChildScrollView(
                              scrollDirection: Axis.horizontal,
                              child: DataTable(
                                columnSpacing: 20,
                                columns: const [
                                  DataColumn(label: Text('Invoice #')),
                                  DataColumn(label: Text('Date')),
                                  DataColumn(label: Text('Customer')),
                                  DataColumn(label: Text('Total CDF'), numeric: true),
                                  DataColumn(label: Text('Status')),
                                ],
                                rows: rows.map((r) => DataRow(cells: [
                                  DataCell(Text(r['transactionNumber']?.toString() ?? '')),
                                  DataCell(Text(_fmtDate(r['saleDate'] as DateTime))),
                                  DataCell(Text(r['customerName']?.toString() ?? '')),
                                  DataCell(Text('CDF ${(r['grandTotal'] as double? ?? 0).toStringAsFixed(0)}')),
                                  DataCell(Text(r['status']?.toString() ?? '')),
                                ])).toList(),
                              ),
                            ),
                          ),
              ),
            ]);
          },
        );
      },
    );
  }
}

// ── Receipts & Reprint Tab ────────────────────────────────────────────────────

class _ReceiptsTab extends StatelessWidget {
  final TextEditingController searchCtrl;
  final DateTime? start;
  final DateTime? end;
  final VoidCallback onSearch;
  final VoidCallback onPickRange;
  final void Function(int saleId) onReprint;

  const _ReceiptsTab({
    required this.searchCtrl,
    required this.start,
    required this.end,
    required this.onSearch,
    required this.onPickRange,
    required this.onReprint,
  });

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ReportBloc, ReportState>(
      builder: (context, state) {
        final ds = state is ReportDataState ? state : const ReportDataState();
        final rows = ds.receiptSearchResults ?? [];
        return Column(children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
            child: Row(children: [
              Expanded(
                child: TextField(
                  controller: searchCtrl,
                  decoration: InputDecoration(
                    hintText: 'Search by invoice # or customer name...',
                    prefixIcon: const Icon(Icons.search, size: 18),
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                    contentPadding: const EdgeInsets.symmetric(vertical: 8),
                    suffixIcon: searchCtrl.text.isNotEmpty
                        ? IconButton(
                            icon: const Icon(Icons.clear, size: 16),
                            onPressed: () {
                              searchCtrl.clear();
                              onSearch();
                            })
                        : null,
                  ),
                  onSubmitted: (_) => onSearch(),
                ),
              ),
              const SizedBox(width: 8),
              TextButton.icon(
                icon: const Icon(Icons.date_range, size: 16),
                label: Text(start != null && end != null
                    ? '${_fmtDate(start!)} – ${_fmtDate(end!)}'
                    : 'All Dates'),
                onPressed: onPickRange,
              ),
              const SizedBox(width: 8),
              FilledButton.icon(
                icon: const Icon(Icons.search, size: 16),
                label: const Text('Search'),
                onPressed: onSearch,
              ),
            ]),
          ),
          Expanded(
            child: ds.isLoadingReceipts
                ? const Center(child: CircularProgressIndicator())
                : rows.isEmpty
                    ? const Center(child: Text('Search for receipts above.'))
                    : SingleChildScrollView(
                        padding: const EdgeInsets.all(16),
                        child: SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: DataTable(
                            columnSpacing: 20,
                            columns: const [
                              DataColumn(label: Text('Invoice #')),
                              DataColumn(label: Text('Date')),
                              DataColumn(label: Text('Customer')),
                              DataColumn(label: Text('Total CDF'), numeric: true),
                              DataColumn(label: Text('Status')),
                              DataColumn(label: Text('Actions')),
                            ],
                            rows: rows.map((r) => DataRow(cells: [
                              DataCell(Text(r['transactionNumber']?.toString() ?? '')),
                              DataCell(Text(_fmtDate(r['saleDate'] as DateTime))),
                              DataCell(Text(r['customerName']?.toString() ?? 'Walk-in')),
                              DataCell(Text('CDF ${(r['grandTotal'] as double? ?? 0).toStringAsFixed(0)}')),
                              DataCell(Text(r['status']?.toString() ?? '')),
                              DataCell(
                                Row(children: [
                                  IconButton(
                                    icon: const Icon(Icons.print_rounded, size: 18),
                                    tooltip: 'Reprint Receipt',
                                    onPressed: () => onReprint(r['id'] as int),
                                  ),
                                ]),
                              ),
                            ])).toList(),
                          ),
                        ),
                      ),
          ),
        ]);
      },
    );
  }
}

// ── Product Sales History Tab ─────────────────────────────────────────────────

class _ProductHistoryTab extends StatelessWidget {
  final DateTime start, end;
  final int? selectedProductId;
  final VoidCallback onPickRange;
  final ValueChanged<int?> onProductChanged;
  final void Function(List<Map<String, dynamic>>) onExportPdf;

  const _ProductHistoryTab({
    required this.start,
    required this.end,
    required this.selectedProductId,
    required this.onPickRange,
    required this.onProductChanged,
    required this.onExportPdf,
  });

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ReportBloc, ReportState>(
      builder: (context, state) {
        final ds = state is ReportDataState ? state : const ReportDataState();
        final rows = ds.productHistory ?? [];
        return BlocBuilder<InventoryBloc, InventoryState>(
          builder: (context, invState) {
            final products = invState is InventoryLoaded ? invState.products : <Product>[];
            return Column(children: [
              Padding(
                padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
                child: Wrap(spacing: 12, crossAxisAlignment: WrapCrossAlignment.center, children: [
                  TextButton.icon(
                    icon: const Icon(Icons.date_range, size: 16),
                    label: Text('${_fmtDate(start)} – ${_fmtDate(end)}'),
                    onPressed: onPickRange,
                  ),
                  DropdownButton<int?>(
                    value: selectedProductId,
                    hint: const Text('All Products'),
                    items: [
                      const DropdownMenuItem(value: null, child: Text('All Products')),
                      ...products.map((p) => DropdownMenuItem(
                          value: p.id, child: Text(p.name))),
                    ],
                    onChanged: onProductChanged,
                  ),
                  if (rows.isNotEmpty)
                    FilledButton.icon(
                      onPressed: () => onExportPdf(rows),
                      icon: const Icon(Icons.picture_as_pdf_rounded, size: 16),
                      label: const Text('Export PDF'),
                    ),
                ]),
              ),
              Expanded(
                child: ds.isLoadingProductHistory
                    ? const Center(child: CircularProgressIndicator())
                    : rows.isEmpty
                        ? const Center(child: Text('No product history found.'))
                        : SingleChildScrollView(
                            padding: const EdgeInsets.all(16),
                            child: SingleChildScrollView(
                              scrollDirection: Axis.horizontal,
                              child: DataTable(
                                columnSpacing: 20,
                                columns: const [
                                  DataColumn(label: Text('Product')),
                                  DataColumn(label: Text('Qty Sold'), numeric: true),
                                  DataColumn(label: Text('Times Sold'), numeric: true),
                                  DataColumn(label: Text('Revenue CDF'), numeric: true),
                                  DataColumn(label: Text('Stock Now'), numeric: true),
                                  DataColumn(label: Text('First Sale')),
                                  DataColumn(label: Text('Last Sale')),
                                ],
                                rows: rows.map((r) => DataRow(cells: [
                                  DataCell(Text(r['name']?.toString() ?? '')),
                                  DataCell(Text((r['totalQtySold'] as double? ?? 0).toStringAsFixed(0))),
                                  DataCell(Text((r['timesTransacted'] as int? ?? 0).toString())),
                                  DataCell(Text('CDF ${(r['totalRevenue'] as double? ?? 0).toStringAsFixed(0)}')),
                                  DataCell(Text(
                                    (r['stockQuantity'] as double? ?? 0).toStringAsFixed(0),
                                    style: TextStyle(
                                      color: (r['stockQuantity'] as double? ?? 0) <= 0
                                          ? Colors.red
                                          : null,
                                    ),
                                  )),
                                  DataCell(Text(r['firstSale'] != null
                                      ? _fmtDate(r['firstSale'] as DateTime)
                                      : '—')),
                                  DataCell(Text(r['lastSale'] != null
                                      ? _fmtDate(r['lastSale'] as DateTime)
                                      : '—')),
                                ])).toList(),
                              ),
                            ),
                          ),
              ),
            ]);
          },
        );
      },
    );
  }
}

// ── Inventory Report Tab ──────────────────────────────────────────────────────

class _InventoryReportTab extends StatelessWidget {
  final VoidCallback onRefresh;
  final void Function(List<Map<String, dynamic>>) onExportPdf;

  const _InventoryReportTab({required this.onRefresh, required this.onExportPdf});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ReportBloc, ReportState>(
      builder: (context, state) {
        final ds = state is ReportDataState ? state : const ReportDataState();
        final rows = ds.inventoryReport ?? [];
        return Column(children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
            child: Row(children: [
              TextButton.icon(
                icon: const Icon(Icons.refresh, size: 16),
                label: const Text('Refresh'),
                onPressed: onRefresh,
              ),
              const Spacer(),
              if (rows.isNotEmpty)
                FilledButton.icon(
                  onPressed: () => onExportPdf(rows),
                  icon: const Icon(Icons.picture_as_pdf_rounded, size: 16),
                  label: const Text('Export PDF'),
                ),
            ]),
          ),
          Expanded(
            child: ds.isLoadingInventoryReport
                ? const Center(child: CircularProgressIndicator())
                : rows.isEmpty
                    ? const Center(child: Text('No inventory data.'))
                    : SingleChildScrollView(
                        padding: const EdgeInsets.all(16),
                        child: SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: DataTable(
                            columnSpacing: 16,
                            columns: const [
                              DataColumn(label: Text('Product')),
                              DataColumn(label: Text('SKU')),
                              DataColumn(label: Text('Category')),
                              DataColumn(label: Text('Stock'), numeric: true),
                              DataColumn(label: Text('Cost CDF'), numeric: true),
                              DataColumn(label: Text('Sell CDF'), numeric: true),
                              DataColumn(label: Text('Total Value'), numeric: true),
                              DataColumn(label: Text('Low?')),
                            ],
                            rows: rows.map((r) => DataRow(
                              color: WidgetStateProperty.resolveWith((states) {
                                if (r['isLowStock'] == true) {
                                  return Colors.red.withAlpha(20);
                                }
                                return null;
                              }),
                              cells: [
                                DataCell(Text(r['name']?.toString() ?? '')),
                                DataCell(Text(r['sku']?.toString() ?? '—')),
                                DataCell(Text(r['category']?.toString() ?? '—')),
                                DataCell(Text((r['stockQuantity'] as double? ?? 0).toStringAsFixed(0))),
                                DataCell(Text('CDF ${(r['costPrice'] as double? ?? 0).toStringAsFixed(0)}')),
                                DataCell(Text('CDF ${(r['sellingPrice'] as double? ?? 0).toStringAsFixed(0)}')),
                                DataCell(Text('CDF ${(r['totalValue'] as double? ?? 0).toStringAsFixed(0)}')),
                                DataCell(r['isLowStock'] == true
                                    ? const Icon(Icons.warning_rounded, color: Colors.orange, size: 18)
                                    : const SizedBox.shrink()),
                              ],
                            )).toList(),
                          ),
                        ),
                      ),
          ),
        ]);
      },
    );
  }
}

// ── Expense Report Tab ────────────────────────────────────────────────────────

class _ExpenseReportTab extends StatelessWidget {
  final DateTime start, end;
  final VoidCallback onPickRange;
  final void Function(List<Map<String, dynamic>>) onExportPdf;

  const _ExpenseReportTab({
    required this.start,
    required this.end,
    required this.onPickRange,
    required this.onExportPdf,
  });

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ReportBloc, ReportState>(
      builder: (context, state) {
        final ds = state is ReportDataState ? state : const ReportDataState();
        final rows = ds.expenseReport ?? [];
        return Column(children: [
          _ReportToolbar(
            label: '${_fmtDate(start)} – ${_fmtDate(end)}',
            onPickRange: onPickRange,
            isLoading: ds.isLoadingExpenseReport,
            hasData: rows.isNotEmpty,
            onExport: () => onExportPdf(rows),
          ),
          Expanded(
            child: ds.isLoadingExpenseReport
                ? const Center(child: CircularProgressIndicator())
                : rows.isEmpty
                    ? const Center(child: Text('No expenses in selected range.'))
                    : SingleChildScrollView(
                        padding: const EdgeInsets.all(16),
                        child: SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: DataTable(
                            columnSpacing: 20,
                            columns: const [
                              DataColumn(label: Text('Date')),
                              DataColumn(label: Text('Category')),
                              DataColumn(label: Text('Description')),
                              DataColumn(label: Text('Amount CDF'), numeric: true),
                            ],
                            rows: rows.map((r) => DataRow(cells: [
                              DataCell(Text(_fmtDate(r['date'] as DateTime))),
                              DataCell(Text(r['category']?.toString() ?? '—')),
                              DataCell(Text(r['description']?.toString() ?? '')),
                              DataCell(Text('CDF ${(r['amount'] as double? ?? 0).toStringAsFixed(0)}')),
                            ])).toList(),
                          ),
                        ),
                      ),
          ),
          if (rows.isNotEmpty)
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 8),
              color: Theme.of(context).colorScheme.surfaceContainerLow,
              child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [
                Text(
                  'Total: CDF ${rows.fold<double>(0, (s, r) => s + (r['amount'] as double? ?? 0)).toStringAsFixed(0)}',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
                ),
              ]),
            ),
        ]);
      },
    );
  }
}

// ── Shared toolbar ───────────────────────────────────────────────────────────

class _ReportToolbar extends StatelessWidget {
  final String label;
  final VoidCallback onPickRange;
  final bool isLoading;
  final bool hasData;
  final VoidCallback onExport;

  const _ReportToolbar({
    required this.label,
    required this.onPickRange,
    required this.isLoading,
    required this.hasData,
    required this.onExport,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
      child: Row(children: [
        TextButton.icon(
          icon: const Icon(Icons.date_range, size: 16),
          label: Text(label),
          onPressed: onPickRange,
        ),
        if (isLoading) ...[
          const SizedBox(width: 12),
          const SizedBox(
            width: 16,
            height: 16,
            child: CircularProgressIndicator(strokeWidth: 2),
          ),
        ],
        const Spacer(),
        if (hasData)
          FilledButton.icon(
            onPressed: onExport,
            icon: const Icon(Icons.picture_as_pdf_rounded, size: 16),
            label: const Text('Export PDF'),
          ),
      ]),
    );
  }
}

