import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../bloc/report_bloc.dart';

class ReportScreen extends StatefulWidget {
  const ReportScreen({super.key});

  @override
  State<ReportScreen> createState() => _ReportScreenState();
}

class _ReportScreenState extends State<ReportScreen> {
  DateTime _selectedDate = DateTime.now();

  @override
  void initState() {
    super.initState();
    _refresh();
  }

  void _refresh() {
    context.read<ReportBloc>().add(LoadDailySalesSummary(_selectedDate));
    context.read<ReportBloc>().add(LoadInventoryValuation());
  }

  Future<void> _exportPdf(ReportDataState state) async {
    final doc = pw.Document();

    final dateStr = '${_selectedDate.day.toString().padLeft(2,'0')}/'
        '${_selectedDate.month.toString().padLeft(2,'0')}/'
        '${_selectedDate.year}';

    pw.TextStyle h1()  => pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold);
    pw.TextStyle h2()  => pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold);
    pw.TextStyle body() => const pw.TextStyle(fontSize: 11);

    final s     = state.dailySummary;
    final total = state.inventoryValuation;

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (ctx) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Center(child: pw.Text('POS Africa — Business Report', style: h1())),
              pw.Center(child: pw.Text('Date: $dateStr', style: body())),
              pw.SizedBox(height: 16),
              pw.Divider(thickness: 1),
              pw.SizedBox(height: 12),

              // Daily Sales
              pw.Text('Daily Sales Summary', style: h2()),
              pw.SizedBox(height: 8),
              if (s != null) ...[
                pw.Table(
                  border: pw.TableBorder.all(color: PdfColors.grey300),
                  columnWidths: {
                    0: const pw.FlexColumnWidth(2),
                    1: const pw.FlexColumnWidth(1),
                  },
                  children: [
                    pw.TableRow(
                      decoration: const pw.BoxDecoration(color: PdfColors.blueGrey100),
                      children: [
                        pw.Padding(padding: const pw.EdgeInsets.all(6),
                            child: pw.Text('Metric', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11))),
                        pw.Padding(padding: const pw.EdgeInsets.all(6),
                            child: pw.Text('Value', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11))),
                      ],
                    ),
                    _pdfTableRow('Transactions',   s['count']?.toStringAsFixed(0) ?? '0'),
                    _pdfTableRow('Total Revenue',  'CDF ${s['total']?.toStringAsFixed(0) ?? '0'}'),
                    _pdfTableRow('Total Discounts','CDF ${s['discount']?.toStringAsFixed(0) ?? '0'}'),
                  ],
                ),
              ] else
                pw.Text('No sales data for this date.', style: body()),

              pw.SizedBox(height: 20),

              // Inventory
              pw.Text('Inventory Summary', style: h2()),
              pw.SizedBox(height: 8),
              if (total != null)
                pw.Table(
                  border: pw.TableBorder.all(color: PdfColors.grey300),
                  columnWidths: {
                    0: const pw.FlexColumnWidth(2),
                    1: const pw.FlexColumnWidth(1),
                  },
                  children: [
                    pw.TableRow(
                      decoration: const pw.BoxDecoration(color: PdfColors.blueGrey100),
                      children: [
                        pw.Padding(padding: const pw.EdgeInsets.all(6),
                            child: pw.Text('Metric', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11))),
                        pw.Padding(padding: const pw.EdgeInsets.all(6),
                            child: pw.Text('Value', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11))),
                      ],
                    ),
                    _pdfTableRow('Total Inventory Value (Cost)', 'CDF ${total.toStringAsFixed(0)}'),
                  ],
                )
              else
                pw.Text('Inventory data not loaded.', style: body()),

              pw.Spacer(),
              pw.Divider(),
              pw.Center(
                child: pw.Text(
                  'Generated by POS Africa  •  ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
                  style: body(),
                ),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (_) async => doc.save(),
      name: 'POS_Africa_Report_$dateStr'.replaceAll('/', '-'),
    );
  }

  pw.TableRow _pdfTableRow(String label, String value) {
    return pw.TableRow(
      children: [
        pw.Padding(padding: const pw.EdgeInsets.all(6),
            child: pw.Text(label, style: pw.TextStyle(fontSize: 11))),
        pw.Padding(padding: const pw.EdgeInsets.all(6),
            child: pw.Text(value, style: pw.TextStyle(fontSize: 11))),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Reports & Analytics'),
        actions: [
          TextButton.icon(
            icon: const Icon(Icons.calendar_today),
            label: Text('${_selectedDate.day}/${_selectedDate.month}/${_selectedDate.year}'),
            onPressed: () async {
              final picked = await showDatePicker(
                context: context,
                initialDate: _selectedDate,
                firstDate: DateTime(2020),
                lastDate: DateTime.now(),
              );
              if (picked != null) {
                setState(() => _selectedDate = picked);
                _refresh();
              }
            },
          ),
          BlocBuilder<ReportBloc, ReportState>(
            builder: (context, state) {
              final ready = state is ReportDataState &&
                  !state.isLoadingDaily &&
                  !state.isLoadingInventory;
              return IconButton(
                icon: const Icon(Icons.picture_as_pdf_outlined),
                tooltip: 'Export A4 PDF',
                onPressed: ready
                    ? () => _exportPdf(state as ReportDataState)
                    : null,
              );
            },
          ),
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: _refresh,
          ),
        ],
      ),
      body: BlocBuilder<ReportBloc, ReportState>(
        builder: (context, state) {
          return SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Daily Sales Summary', style: Theme.of(context).textTheme.titleLarge),
                const SizedBox(height: 16),
                _buildSalesCards(state),
                const SizedBox(height: 48),
                Text('Inventory Status', style: Theme.of(context).textTheme.titleLarge),
                const SizedBox(height: 16),
                _buildInventoryCard(state),
                const SizedBox(height: 48),
                // TODO: Add Top Selling Products chart/list
              ],
            ),
          );
        },
      ),
    );
  }

  Widget _buildSalesCards(ReportState state) {
    if (state is! ReportDataState) return const LinearProgressIndicator();
    if (state.isLoadingDaily) return const LinearProgressIndicator();
    if (state.error != null) return Text('Error: ${state.error}', style: const TextStyle(color: Colors.red));
    final s = state.dailySummary;
    if (s == null) return const SizedBox();
    return Row(
      children: [
        _ReportCard(label: 'Transactions', value: s['count']?.toStringAsFixed(0) ?? '0', icon: Icons.receipt),
        const SizedBox(width: 16),
        _ReportCard(label: 'Total Revenue', value: 'CDF ${s['total']?.toStringAsFixed(0) ?? '0'}', icon: Icons.payments, color: Colors.green),
        const SizedBox(width: 16),
        _ReportCard(label: 'Total Discounts', value: 'CDF ${s['discount']?.toStringAsFixed(0) ?? '0'}', icon: Icons.local_offer, color: Colors.orange),
      ],
    );
  }

  Widget _buildInventoryCard(ReportState state) {
    if (state is! ReportDataState) return const SizedBox();
    if (state.isLoadingInventory) return const LinearProgressIndicator();
    final total = state.inventoryValuation;
    if (total == null) return const SizedBox();
    return Row(
      children: [
        _ReportCard(
          label: 'Total Inventory Value (Cost)',
          value: 'CDF ${total.toStringAsFixed(0)}',
          icon: Icons.inventory,
          color: Colors.blue,
        ),
      ],
    );
  }
}

class _ReportCard extends StatelessWidget {
  final String label;
  final String value;
  final IconData icon;
  final Color? color;

  const _ReportCard({required this.label, required this.value, required this.icon, this.color});

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Card(
        elevation: 2,
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(icon, color: color ?? Theme.of(context).colorScheme.primary, size: 32),
              const SizedBox(height: 16),
              Text(label, style: const TextStyle(color: Colors.grey, fontSize: 14)),
              const SizedBox(height: 8),
              Text(value, style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
            ],
          ),
        ),
      ),
    );
  }
}
